version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt install -y build-essential apt-transport-https lsb-release ca-certificates curl
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - cd front-end
      - npm install
      - npm run build
      - cd ../back-end
      - npm install


  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - ls -alh
      - ls -alh ..